name: Random daily commits

on:
  schedule:
    # Run at multiple anchor times per day
    - cron: '0 6 * * *'   # ~6 AM UTC
    - cron: '0 12 * * *'  # ~12 PM UTC
    - cron: '0 18 * * *'  # ~6 PM UTC
    - cron: '0 23 * * *'  # ~11 PM UTC
  workflow_dispatch: {}

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Random delay
        run: |
          # Sleep for 0–3 hours to add randomness
          delay=$((RANDOM % 10800))
          echo "Sleeping for $delay seconds..."
          sleep $delay

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "Last run: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > .daily-timestamp.txt

      - name: Commit & push
        run: |
         git config user.name "github-actions[bot]"
         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Automated daily commit: $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
         git pull --rebase
         git push
