name: Random daily commits

on:
  schedule:
    - cron: '0 6 * * *'    # 06:00 UTC
    - cron: '0 12 * * *'   # 12:00 UTC
    - cron: '0 18 * * *'   # 18:00 UTC
    - cron: '0 23 * * *'   # 23:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: random-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Random delay (0–90 min)
        run: |
          delay=$((RANDOM % 5400))
          echo "Sleeping $delay seconds..."
          sleep "$delay"

      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Configure Git (credit commits to Lance)
        env:
          GIT_AUTHOR_NAME: "Lance W. Harlan"
          GIT_COMMITTER_NAME: "Lance W. Harlan"
          GIT_AUTHOR_EMAIL: "11446075+harlanlw@users.noreply.github.com"
          GIT_COMMITTER_EMAIL: "11446075+harlanlw@users.noreply.github.com"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git config author.name     "$GIT_AUTHOR_NAME"
          git config author.email    "$GIT_AUTHOR_EMAIL"
          git config committer.name  "$GIT_COMMITTER_NAME"
          git config committer.email "$GIT_COMMITTER_EMAIL"

      - name: Rebase onto remote (pre-change)
        run: |
          branch="${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}"
          git fetch origin "$branch"
          git checkout "$branch"
          git pull --rebase --autostash origin "$branch"

      - name: Update timestamp (creates a change)
        run: |
          echo "Last run: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > .daily-timestamp.txt

      - name: Commit (if changed)
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Automated commit: $(date -u +'%Y-%m-%d %H:%M:%S')"

      - name: Push with retry (handles races)
        run: |
          branch="${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}"
          for i in 1 2 3; do
            if git push origin "$branch"; then
              echo "Push succeeded."
              exit 0
            fi
            echo "Push failed (attempt $i). Re-pulling and retrying..."
            git pull --rebase --autostash origin "$branch"
            sleep 5
          done
          echo "Push failed after retries."
          exit 1
